"""initial schema

Revision ID: 15111a3648bd
Revises: 
Create Date: 2026-07-14 12:08:17.872712

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '15111a3648bd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector extension must exist before any Vector column is created
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clients',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='clientstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('organization_admin', 'finance_manager', 'project_manager', 'reviewer', 'read_only', name='userrole', native_enum=False, length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_org_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'on_hold', 'completed', 'archived', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('master_service_agreement', 'statement_of_work', 'amendment', 'change_order', 'rate_card', 'customer_request', 'invoice', 'other', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('extraction_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'unreadable', name='extractionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('superseded_by_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index('ix_documents_org_sha256', 'documents', ['organization_id', 'sha256'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('invoices',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved_draft', 'issued', 'paid', 'void', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), nullable=False),
    sa.Column('tax_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'invoice_number', name='uq_invoices_number')
    )
    op.create_index('ix_invoices_org_project', 'invoices', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index('ix_invoices_period', 'invoices', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_table('review_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'completed_with_errors', 'failed', name='reviewrunstatus', native_enum=False, length=30), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_runs_org_project', 'review_runs', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_review_runs_organization_id'), 'review_runs', ['organization_id'], unique=False)
    op.create_index('ix_review_runs_period', 'review_runs', ['project_id', 'billing_period_start', 'billing_period_end'], unique=False)
    op.create_table('work_items',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_system', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'cancelled', name='workitemstatus', native_enum=False, length=20), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('created_at_external', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at_external', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_system', 'external_id', name='uq_work_items_external')
    )
    op.create_index('ix_work_items_org_project', 'work_items', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_work_items_organization_id'), 'work_items', ['organization_id'], unique=False)
    op.create_table('contracts',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'expired', 'terminated', name='contractstatus', native_enum=False, length=20), nullable=False),
    sa.Column('governing_document_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_user', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['governing_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contracts_effective', 'contracts', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_contracts_org_client', 'contracts', ['organization_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('customer_requests',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('linked_work_item_id', sa.UUID(), nullable=True),
    sa.Column('customer_authorization_status', sa.Enum('none', 'verbal_claimed', 'written', 'disputed', name='authorizationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['linked_work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_requests_org_project', 'customer_requests', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_customer_requests_organization_id'), 'customer_requests', ['organization_id'], unique=False)
    op.create_table('findings',
    sa.Column('review_run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.Enum('potentially_out_of_scope', 'exhausted_allowance', 'unbilled_time', 'rate_mismatch', 'possible_duplicate', 'already_invoiced', 'missing_customer_authorization', 'insufficient_evidence', 'contract_ambiguity', name='findingtype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('in_scope', 'potentially_out_of_scope', 'clearly_out_of_scope', 'insufficient_information', name='classification', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('potential_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('value_unavailable_reason', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'approved_for_followup', 'approved_for_billing', 'rejected', 'needs_more_evidence', 'already_resolved', name='reviewstatus', native_enum=False, length=30), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=10), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradicting_summary', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_findings_confidence'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_dedup', 'findings', ['organization_id', 'dedup_key'], unique=False)
    op.create_index('ix_findings_org_project', 'findings', ['organization_id', 'project_id'], unique=False)
    op.create_index('ix_findings_org_status', 'findings', ['organization_id', 'review_status'], unique=False)
    op.create_index(op.f('ix_findings_organization_id'), 'findings', ['organization_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_item_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('employee_role', sa.String(length=100), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('billable_status', sa.Enum('billable', 'non_billable', 'unknown', name='billablestatus', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('minutes > 0', name='ck_time_entries_positive_minutes'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_entries_org_hash', 'time_entries', ['organization_id', 'content_hash'], unique=False)
    op.create_index('ix_time_entries_org_project_date', 'time_entries', ['organization_id', 'project_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_time_entries_organization_id'), 'time_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_time_entries_work_item_id'), 'time_entries', ['work_item_id'], unique=False)
    op.create_table('contract_clauses',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('clause_type', sa.Enum('included_service', 'excluded_service', 'deliverable', 'support_allowance', 'hourly_rate', 'fixed_fee', 'approval_requirement', 'change_control', 'expense_rule', 'payment_term', 'other', name='clausetype', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('normalized_interpretation', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_reference', sa.String(length=120), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_clause_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_clause_confidence'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_clause_id'], ['contract_clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clauses_effective', 'contract_clauses', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_clauses_org_contract', 'contract_clauses', ['organization_id', 'contract_id'], unique=False)
    op.create_index(op.f('ix_contract_clauses_organization_id'), 'contract_clauses', ['organization_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.Enum('contract_clause', 'work_item', 'time_entry', 'customer_request', 'invoice', 'invoice_line', 'document', 'calculation', name='evidencetype', native_enum=False, length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('quotation', sa.Text(), nullable=True),
    sa.Column('document_page', sa.Integer(), nullable=True),
    sa.Column('section_reference', sa.String(length=120), nullable=True),
    sa.Column('relevance_explanation', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_evidence_org_finding', 'finding_evidence', ['organization_id', 'finding_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_organization_id'), 'finding_evidence', ['organization_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('internal_review_summary', 'change_order_draft', 'invoice_narrative', 'clarification_email', 'evidence_report', name='artifacttype', native_enum=False, length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_by_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('approved_by_user', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_artifacts_org_finding', 'generated_artifacts', ['organization_id', 'finding_id'], unique=False)
    op.create_index(op.f('ix_generated_artifacts_organization_id'), 'generated_artifacts', ['organization_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('linked_work_item_id', sa.UUID(), nullable=True),
    sa.Column('linked_time_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_invoice_lines_quantity'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_time_entry_id'], ['time_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_lines_org_invoice', 'invoice_lines', ['organization_id', 'invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_organization_id'), 'invoice_lines', ['organization_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('previous_status', sa.Enum('pending', 'approved_for_followup', 'approved_for_billing', 'rejected', 'needs_more_evidence', 'already_resolved', name='reviewstatus', native_enum=False, length=30), nullable=False),
    sa.Column('new_status', sa.Enum('pending', 'approved_for_followup', 'approved_for_billing', 'rejected', 'needs_more_evidence', 'already_resolved', name='reviewstatus', native_enum=False, length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_decisions_org_finding', 'review_decisions', ['organization_id', 'finding_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_organization_id'), 'review_decisions', ['organization_id'], unique=False)
    op.create_table('allowances',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('allowance_type', sa.Enum('support_hours', 'implementation_hours', 'other', name='allowancetype', native_enum=False, length=40), nullable=False),
    sa.Column('included_quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recurrence', sa.Enum('monthly', 'quarterly', 'annual', 'total', name='allowancerecurrence', native_enum=False, length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('included_quantity >= 0', name='ck_allowance_nonnegative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['contract_clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allowances_org_contract', 'allowances', ['organization_id', 'contract_id'], unique=False)
    op.create_index(op.f('ix_allowances_organization_id'), 'allowances', ['organization_id'], unique=False)
    op.create_table('clause_embeddings',
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_reference', sa.String(length=120), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['contract_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clause_embeddings_clause_id'), 'clause_embeddings', ['clause_id'], unique=False)
    op.create_index(op.f('ix_clause_embeddings_document_id'), 'clause_embeddings', ['document_id'], unique=False)
    op.create_index('ix_clause_embeddings_org', 'clause_embeddings', ['organization_id'], unique=False)
    # ANN index for cosine retrieval (HNSW works with any row count)
    op.execute(
        "CREATE INDEX ix_clause_embeddings_hnsw ON clause_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_index(op.f('ix_clause_embeddings_organization_id'), 'clause_embeddings', ['organization_id'], unique=False)
    op.create_table('rate_rules',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('hourly_rate_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('hourly_rate_minor >= 0', name='ck_rate_nonnegative'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['contract_clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_rules_effective', 'rate_rules', ['effective_from', 'effective_to'], unique=False)
    op.create_index('ix_rate_rules_org_contract', 'rate_rules', ['organization_id', 'contract_id'], unique=False)
    op.create_index(op.f('ix_rate_rules_organization_id'), 'rate_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_rules_organization_id'), table_name='rate_rules')
    op.drop_index('ix_rate_rules_org_contract', table_name='rate_rules')
    op.drop_index('ix_rate_rules_effective', table_name='rate_rules')
    op.drop_table('rate_rules')
    op.drop_index(op.f('ix_clause_embeddings_organization_id'), table_name='clause_embeddings')
    op.execute("DROP INDEX IF EXISTS ix_clause_embeddings_hnsw")
    op.drop_index('ix_clause_embeddings_org', table_name='clause_embeddings')
    op.drop_index(op.f('ix_clause_embeddings_document_id'), table_name='clause_embeddings')
    op.drop_index(op.f('ix_clause_embeddings_clause_id'), table_name='clause_embeddings')
    op.drop_table('clause_embeddings')
    op.drop_index(op.f('ix_allowances_organization_id'), table_name='allowances')
    op.drop_index('ix_allowances_org_contract', table_name='allowances')
    op.drop_table('allowances')
    op.drop_index(op.f('ix_review_decisions_organization_id'), table_name='review_decisions')
    op.drop_index('ix_review_decisions_org_finding', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_invoice_lines_organization_id'), table_name='invoice_lines')
    op.drop_index('ix_invoice_lines_org_invoice', table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_generated_artifacts_organization_id'), table_name='generated_artifacts')
    op.drop_index('ix_generated_artifacts_org_finding', table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_finding_evidence_organization_id'), table_name='finding_evidence')
    op.drop_index('ix_finding_evidence_org_finding', table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_contract_clauses_organization_id'), table_name='contract_clauses')
    op.drop_index('ix_clauses_org_contract', table_name='contract_clauses')
    op.drop_index('ix_clauses_effective', table_name='contract_clauses')
    op.drop_table('contract_clauses')
    op.drop_index(op.f('ix_time_entries_work_item_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_organization_id'), table_name='time_entries')
    op.drop_index('ix_time_entries_org_project_date', table_name='time_entries')
    op.drop_index('ix_time_entries_org_hash', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index(op.f('ix_findings_organization_id'), table_name='findings')
    op.drop_index('ix_findings_org_status', table_name='findings')
    op.drop_index('ix_findings_org_project', table_name='findings')
    op.drop_index('ix_findings_dedup', table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_customer_requests_organization_id'), table_name='customer_requests')
    op.drop_index('ix_customer_requests_org_project', table_name='customer_requests')
    op.drop_table('customer_requests')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_index('ix_contracts_org_client', table_name='contracts')
    op.drop_index('ix_contracts_effective', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_work_items_organization_id'), table_name='work_items')
    op.drop_index('ix_work_items_org_project', table_name='work_items')
    op.drop_table('work_items')
    op.drop_index('ix_review_runs_period', table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_organization_id'), table_name='review_runs')
    op.drop_index('ix_review_runs_org_project', table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index('ix_invoices_period', table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index('ix_invoices_org_project', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_sha256', table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_org_created', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
